name: Deploy WordPress Theme

on:
  push:
    branches:
      - staging
      - master

jobs:
  deploy:
    name: Deploy to Staging or Production
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14' # Specify the Node.js version you need

    - name: Install dependencies
      run: |
        cd wp-content/themes/perlui_theme
        yarn install

    - name: Build project
      run: |
        cd wp-content/themes/perlui_theme
        yarn build

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Deploy to Staging
      if: github.ref == 'refs/heads/staging'
      env:
        SERVER: ${{ secrets.SERVER }}
        USER: ${{ secrets.USER }}
      run: |
        STAGING_PATH=domains/staging.fornax.digital/public_html/wp-content/themes/perlui_theme/
        ssh $USER@$SERVER "mkdir -p $STAGING_PATH"
        rsync -avz --delete --exclude '.git' --exclude 'node_modules' wp-content/themes/perlui_theme/ $USER@$SERVER:$STAGING_PATH
        ssh $USER@$SERVER "wp db export --path=domains/staging.fornax.digital/public_html/ && wp db import /path/to/your-local-db.sql --path=domains/staging.fornax.digital/public_html/"
        ssh $USER@$SERVER "wp plugin activate --all --path=domains/staging.fornax.digital/public_html/"
        ssh $USER@$SERVER "wp theme activate perlui_theme --path=domains/staging.fornax.digital/public_html/"

    - name: Deploy to Production
      if: github.ref == 'refs/heads/master'
      env:
        SERVER: ${{ secrets.SERVER }}
        USER: ${{ secrets.USER }}
      run: |
        PRODUCTION_PATH=domains/fornax.digital/public_html/wp-content/themes/perlui_theme/
        ssh $USER@$SERVER "mkdir -p $PRODUCTION_PATH"
        rsync -avz --delete --exclude '.git' --exclude 'node_modules' wp-content/themes/perlui_theme/ $USER@$SERVER:$PRODUCTION_PATH
        ssh $USER@$SERVER "wp db export --path=domains/fornax.digital/public_html/ && wp db import /path/to/your-local-db.sql --path=domains/fornax.digital/public_html/"
        ssh $USER@$SERVER "wp plugin activate --all --path=domains/fornax.digital/public_html/"
        ssh $USER@$SERVER "wp theme activate perlui_theme --path=domains/fornax.digital/public_html/"
